- match:
    dependency_type: "development"
    update_type: "all"
- match:
    dependency_type: "production"
    update_type: "semver:patch"
- match:
    dependency_name: "github.com/stretchr/testify"
    update_type: "all"
- match:
    dependency_name: "github.com/jarcoal/httpmock"
    update_type: "all"
- match:
    dependency_name: "google.golang.org/api"
    update_type: "semver:minor"
- match:
    dependency_name: "google.golang.org/genproto"
    update_type: "semver:minor"
- match:
    dependency_name: "google.golang.org/grpc"
    update_type: "semver:minor"
- match:
    dependency_name: "github.com/getsentry/sentry-go"
    update_type: "semver:minor"
- match:
    dependency_name: "@sentry/*"
    update_type: "semver:minor"
