version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - sue445

  - package-ecosystem: gomod
    directory: "/function"
    schedule:
      interval: daily
      time: "05:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 99
    assignees:
      - sue445
    labels:
      - dependencies
      - go
      - function

  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: daily
      time: "05:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 99
    assignees:
      - sue445
    labels:
      - dependencies
      - javascript
      - frontend
    ignore:
      - dependency-name: "firebase"
        versions:
          - ">= 8.0" # c.f. https://github.com/sue445/primap/issues/643
    groups:
      sentry-dependencies:
        patterns:
          - "@sentry/*"
