steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'primap'
      - '--image'
      - 'asia.gcr.io/primap/primap:${COMMIT_SHA}'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--concurrency'
      - '80'
      - '--port'
      - '8000'
      - '--allow-unauthenticated'
      - '--cpu'
      - '500m'
      - '--memory'
      - '256Mi'
      - '--max-instances'
      - 'default'
      - '--service-account'
      - 'cloud-run-manager@primap.iam.gserviceaccount.com'
