version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - gopath-data:/go
    ports:
      - "8000:8000"
    environment:
      PORT: 8000

volumes:
  gopath-data:
    driver: local
