version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - gopath-data:/go
    environment:
      SENTRY_DSN: ${SENTRY_DSN}
      SENTRY_ENVIRONMENT: development
      SENTRY_DEBUG: "true"
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      PUBSUB_PROJECT_ID: test
      PUBSUB_EMULATOR_HOST: localhost:8085

volumes:
  gopath-data:
    driver: local
