# c.f. https://dependabot.com/docs/config-file/
version: 1

update_configs:
  - package_manager: "go:modules"

    directory: "/function/"

    default_labels:
      - dependencies
      - go
      - function

    update_schedule: "daily"

    default_assignees:
      - sue445

    automerged_updates:
      - match:
          update_type: "semver:patch"
      - match:
          dependency_name: "github.com/stretchr/testify"
          update_type: "all"
      - match:
          dependency_name: "github.com/golang/mock"
          update_type: "all"
      - match:
          dependency_name: "github.com/getsentry/sentry-go"
          update_type: "semver:minor"

  - package_manager: "javascript"

    directory: "/function/"

    default_labels:
      - dependencies
      - javascript
      - function

    update_schedule: "daily"

    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "semver:patch"

    default_assignees:
      - sue445

    version_requirement_updates: "auto"

  - package_manager: "javascript"

    directory: "/frontend/"

    default_labels:
      - dependencies
      - javascript
      - frontend

    update_schedule: "daily"

    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "semver:patch"
      - match:
          dependency_name: "@sentry/*"
          update_type: "semver:minor"

    default_assignees:
      - sue445

    version_requirement_updates: "auto"
