@startuml
interface "Cloud Scheduler" as CloudScheduler
note right of CloudScheduler : Runs once a day

agent CronUpdateShops
agent QueueSaveShop as QueueSaveShop1
agent QueueSaveShop as QueueSaveShop2
agent QueueSaveShop as QueueSaveShop3
database "Cloud Firestore" as CloudFirestore

CloudScheduler -down-> CronUpdateShops
CronUpdateShops -down-> QueueSaveShop1
CronUpdateShops -down-> QueueSaveShop2
CronUpdateShops -down-> QueueSaveShop3
QueueSaveShop1 -down-> CloudFirestore
QueueSaveShop2 -down-> CloudFirestore
QueueSaveShop3 -down-> CloudFirestore
@enduml
