name: build-server

on:
  push:
    branches:
      - master
    paths-ignore:
      # Ignore files that are not used in production
      - "**.md"
      - ".env.example"
      - "docker-compose.yml"
      - "Dockerfile-dev-*"
      - "LICENSE"

      # Ignore files used only by the frontend
      - "firebase/**"
      - "frontend/**"
      - "package**.json"
      - "prettier.config.js"
      - "tsconfig.json"
      - "webpack.config.js"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      # Ignore files that are not used in production
      - "**.md"
      - ".env.example"
      - "docker-compose.yml"
      - "Dockerfile-dev-*"
      - "LICENSE"

      # Ignore files used only by the frontend
      - "firebase/**"
      - "frontend/**"
      - "package**.json"
      - "prettier.config.js"
      - "tsconfig.json"
      - "webpack.config.js"

env:
  GO_VERSION: 1.13
  GO111MODULE: "on"
  TEST_ARGS: -coverprofile coverage.out -covermode atomic
  NODE_VERSION: 14

jobs:
  test:
    name: test

    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: v1-${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            v1-${{ runner.os }}-go-${{ env.GO_VERSION }}-

      - name: Install firebase emulator
        run: |
          set -xe
          sudo wget https://firebase.tools/bin/linux/latest -O /usr/local/bin/firebase
          sudo chmod 755 /usr/local/bin/firebase
          firebase setup:emulators:firestore
          firebase setup:emulators:pubsub

      - name: Run test
        run: |
          set -xe
          firebase --project $GCP_PROJECT emulators:exec --only firestore,pubsub "make test"
          firebase --project $GCP_PROJECT emulators:exec --only firestore,pubsub "make testrace"
        env:
          GCP_PROJECT: test

      - name: Slack Notification (not success)
        uses: homoluctus/slatify@master
        if: "! success()"
        continue-on-error: true
        with:
          job_name: ${{ format('*test* ({0})', env.GO_VERSION) }}
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: lint

    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: v1-${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            v1-${{ runner.os }}-go-${{ env.GO_VERSION }}-

      - name: Run lint
        run: |
          set -xe

          export GOPATH=`go env GOPATH`
          export PATH=$GOPATH/bin:$PATH
          go get -u golang.org/x/lint/golint

          make fmtci
          make vet
          make lint

      - name: Slack Notification (not success)
        uses: homoluctus/slatify@master
        if: "! success()"
        continue-on-error: true
        with:
          job_name: "*lint*"
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}

  go2ts:
    name: go2ts

    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: v1-${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            v1-${{ runner.os }}-go-${{ env.GO_VERSION }}-

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/cache@v2
        with:
          path: node_modules/
          key: v1-${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            v1-${{ runner.os }}-node-${{ env.NODE_VERSION }}-

      - run: npm install

      - name: "[NOTE] Run `make go2ts` if this is failed"
        run: |
          set -xe

          export GOPATH=`go env GOPATH`
          export PATH=$GOPATH/bin:$PATH

          go get -u github.com/tkrajina/typescriptify-golang-structs/tscriptify

          make go2ts
          git checkout HEAD -- go.mod go.sum
          git --no-pager diff
          git status | grep "nothing to commit, working tree clean"

      - name: Slack Notification (not success)
        uses: homoluctus/slatify@master
        if: "! success()"
        continue-on-error: true
        with:
          job_name: "*go2ts*"
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: build

    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - run: docker build .

      - name: Slack Notification (not success)
        uses: homoluctus/slatify@master
        if: "! success()"
        continue-on-error: true
        with:
          job_name: "*build*"
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}

  notify:
    needs:
      - test
      - lint
      - go2ts
      - build

    runs-on: ubuntu-latest

    steps:
      - name: Slack Notification (success)
        uses: homoluctus/slatify@master
        if: always()
        continue-on-error: true
        with:
          job_name: '*build-server*'
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}
