name: frontend-build

on:
  push:
    branches:
      - master
    paths-ignore:
      # Ignore files that are not used in production
      - "**.md"
      - "LICENSE"

      # Ignore files used only by the function
      - "function/**"
      - ".github/workflows/function-*.yml"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      # Ignore files that are not used in production
      - "**.md"
      - ".github/workflows/go-mod-tidy-pr.yml"
      - "LICENSE"

      # Ignore files used only by the function
      - "function/**"
      - ".github/workflows/function-*.yml"

env:
  NODE_VERSION: 14

defaults:
  run:
    working-directory: frontend

jobs:
  test:
    name: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/cache@v2
        with:
          path: frontend/node_modules/
          key: frontend-v1-${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            frontend-v1-${{ runner.os }}-node-${{ env.NODE_VERSION }}-

      - run: npm install
      - run: npm test

      - name: Slack Notification (not success)
        uses: lazy-actions/slatify@master
        if: "! success()"
        continue-on-error: true
        with:
          job_name: "*test*"
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}

  webpack:
    name: webpack

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/cache@v2
        with:
          path: frontend/node_modules/
          key: frontend-v1-${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            frontend-v1-${{ runner.os }}-node-${{ env.NODE_VERSION }}-

      - run: npm install
      - run: npm run build
        env:
          NODE_ENV: production
          REACT_APP_GOOGLE_BROWSER_API_KEY: ""
          REACT_APP_SENTRY_DSN: ""
          REACT_APP_SENTRY_RELEASE: ${{ github.sha }}

      - name: public/ should have been created
        run: |
          set -xe
          ls -l public/build/
          ls -l public/index.html

      - name: Slack Notification (not success)
        uses: lazy-actions/slatify@master
        if: "! success()"
        continue-on-error: true
        with:
          job_name: "*webpack*"
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/cache@v2
        with:
          path: frontend/node_modules/
          key: frontend-v1-${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            frontend-v1-${{ runner.os }}-node-${{ env.NODE_VERSION }}-

      - run: npm install
      - run: npm run prettier:check

      - name: Slack Notification (not success)
        uses: lazy-actions/slatify@master
        if: "! success()"
        continue-on-error: true
        with:
          job_name: "*lint*"
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}

  notify:
    needs:
      - test
      - webpack
      - lint

    runs-on: ubuntu-latest

    steps:
      - name: Slack Notification (success)
        uses: lazy-actions/slatify@master
        if: always()
        continue-on-error: true
        with:
          job_name: '*notify*'
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}
