name: frontend-build

on:
  push:
    branches:
      - master
    paths-ignore:
      # Ignore files that are not used in production
      - "**.md"
      - "LICENSE"
      - ".github/workflows/dependabot-auto-merge.yml"
      - ".github/dependabot.yml"
      - ".github/dependabot-auto-merge.yml"

      # Ignore files used only by the function
      - "function/**"
      - ".github/workflows/function-*.yml"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      # Ignore files that are not used in production
      - "**.md"
      - "LICENSE"
      - ".github/workflows/dependabot-auto-merge.yml"
      - ".github/dependabot-auto-merge.yml"

      # Ignore files used only by the function
      - "function/**"
      - ".github/workflows/function-*.yml"

defaults:
  run:
    working-directory: frontend

jobs:
  test:
    name: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - run: npm install
      - run: npm test

      - name: Slack Notification (not success)
        uses: act10ns/slack@v2
        if: "! success()"
        continue-on-error: true
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}

  webpack:
    name: webpack

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - run: npm install
      - run: npm run build
        env:
          NODE_ENV: production
          REACT_APP_GOOGLE_BROWSER_API_KEY: ""
          REACT_APP_SENTRY_DSN: ""
          REACT_APP_SENTRY_RELEASE: ${{ github.sha }}

      - name: public/ should have been created
        run: |
          set -xe
          ls -l public/build/
          ls -l public/index.html

      - name: Slack Notification (not success)
        uses: act10ns/slack@v2
        if: "! success()"
        continue-on-error: true
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}

  lint:
    name: lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - run: npm install
      - run: npm run prettier:check

      - name: Slack Notification (not success)
        uses: act10ns/slack@v2
        if: "! success()"
        continue-on-error: true
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}

  notify:
    needs:
      - test
      - webpack
      - lint

    runs-on: ubuntu-latest

    steps:
      - name: Slack Notification (success)
        uses: act10ns/slack@v2
        if: always()
        continue-on-error: true
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
