name: function-deploy

on:
  push:
    branches:
      - master
      - tweak_sentry
    paths-ignore:
      # Ignore files that are not used in production
      - "**.md"
      - ".dependabot/config.yml"
      - ".github/workflows/go-mod-tidy-pr.yml"
      - "LICENSE"

      # Ignore files used only by the frontend
      - "frontend/**"
      - ".github/workflows/frontend-*.yml"

env:
  NODE_VERSION: 14

defaults:
  run:
    working-directory: function

jobs:
  deploy:
    name: serverless

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/cache@v2
        with:
          path: function/node_modules/
          key: function-v1-${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('function/package-lock.json') }}
          restore-keys: |
            function-v1-${{ runner.os }}-node-${{ env.NODE_VERSION }}-

      - run: npm install

      - name: serverless deploy
        run: |
          mkdir -p ~/.gcloud/
          echo "$SERVICE_ACCOUNT_KEY" > ~/.gcloud/keyfile.json
          npm run deploy
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          SLS_DEBUG: "*"

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT_FUNCTION }}
        with:
          environment: production

      - name: Slack Notification
        uses: lazy-actions/slatify@master
        if: always()
        continue-on-error: true
        with:
          job_name: '*serverless*'
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}
